app:
  name: "bluebell"
  mode: "dev"
  port: "8081"

log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "sql_demo"
  max_open_conns: 20
  max_idle_conns: 20

redis:
  host: "127.0.0.1"
  password: ""
  port: 16379
  db: 0
  pool_size: 100